volumes:
  pg-data:
  mq-data:

services:
  db:
    container_name: sozluk-postgres
    image: postgres:18.6-trixie@sha256:86c951e05bf56c93d95d397747fb8820ac76cc3bedb78f43abd83eedbe3666ae
    user: postgres
    env_file: ../../conf/dev/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql

  redis:
    container_name: sozluk-redis
    image: redis:8.10.1-trixie@sha256:8a1efc5f479551822b47424ccae982026b633f28818eab0387348120a61e10e2
    user: redis

  rabbitmq:
    container_name: sozluk-rabbitmq
    image: rabbitmq:4.2.9-alpine@sha256:bed607c376d239d21203e7c04eb4b4a355bec7d64f04335f58aab867c92fe399
    hostname: rabbitmq_local
    volumes:
      - mq-data:/var/lib/rabbitmq

  web:
    container_name: sozluk-web
    build:
      context: ../..
      dockerfile: docker/dev/dev.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    extends:
      file: common.yml
      service: python

  worker: &celery
    container_name: sozluk-worker
    command: celery worker --loglevel INFO --autoscale=4,0
    depends_on:
      - db
      - redis
      - rabbitmq
    extends:
      file: common.yml
      service: python

  beat:
    <<: *celery
    container_name: sozluk-scheduler
    command: celery beat --loglevel INFO
