FROM python:3.10.8-bullseye
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/

RUN apt-get update && apt-get install -y netcat
RUN pip install -r requirements.txt --no-cache-dir
COPY . /code/

ENTRYPOINT ["/code/scripts/entrypoint.dev.sh"]
