[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "django-sozluk"
version = "1.3.0"
dependencies = [
    "Django ~= 4.2",
    "django-uuslug ~= 2.0",
    "django-widget-tweaks~=1.4",
    "graphene-django~=3.0",
    "python-dateutil~=2.8",
    "user-agents~=2.2",
    "Pillow~=9.5",
    "celery~=5.2",
    "django-celery-email~=3.0",
    "psycopg[c]~=3.1",
    "django-redis~=5.2",
    "gunicorn~=20.1"
]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
combine_as_imports = true
line_length = 120
