FROM python:3.11-bullseye
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/

RUN apt-get update && apt-get install -y netcat
RUN pip install -r requirements.txt --no-cache-dir --no-deps
COPY .. /code/

ENTRYPOINT ["/code/docker/scripts/entrypoint.dev.sh"]
