version: '3.7'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    container_name: sozluk_backend
    command: gunicorn djdict.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - static_volume:/usr/src/app/static:rw
      - media_volume:/usr/src/app/media:rw
    expose:
      - 8000
    env_file:
      - ../conf/django.env
    depends_on:
      - db
  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    restart: always
    container_name: sozluk_nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - "80:8080"
    depends_on:
      - web
  db:
    image: postgres:15.4-alpine
    restart: always
    container_name: sozluk_db
    user: postgres
    env_file:
      - ../conf/postgres.env
  redis:
    image: redis:7.2-alpine
    restart: always
    container_name: sozluk_redis
    user: redis
  celery:
    env_file:
      - ../conf/django.env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    container_name: sozluk_celery_worker
    command: celery -A djdict worker -l info
    volumes:
      - media_volume:/usr/src/app/media
    depends_on:
      - db
      - redis
  celery-beat:
    restart: always
    env_file:
      - ../conf/django.env
    volumes:
      - media_volume:/usr/src/app/media
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sozluk_celery_beat
    command: celery -A djdict beat -l info
    depends_on:
      - db
      - redis
volumes:
  static_volume:
  media_volume:
