# Generated by Django 4.2.9 on 2024-05-29 21:13

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_author_lower_email",
                violation_error_message="this e-mail is already in use.",
            ),
        ),
    ]
